In [1]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 1  8 27 64]
[0.         0.69314718 1.09861229 1.38629436]


In [11]:
#log

arr = np.array([1,2,3,4])

print(np.log(arr))
print(np.log2(arr))


[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]


In [20]:
#rounding

print(np.round(2.45))
print(np.ceil(2.45))
print(np.floor(2.45))
print(np.trunc(2.45))



arr = np.array([1,2,3,4,2,1,])
print(np.unique(arr))

print(np.sort(arr))
# -5 -3 -4 ai sob value possitive hoye jabe
print(np.abs(arr))

2.0
3.0
2.0
2.0
[1 2 3 4]
[1 1 2 2 3 4]
