In [3]:
import numpy as np

In [13]:

np_list = np.array([1,2,3,4,4,5])
print(np_list, type(np_list), np_list.dtype)




np_list2 = np.array([1,2,3,4,4,5, "alvin"])
#data base type check korar jhono 
# print(np_list2, type(np_list2) , np_list2.dtype)


#shape check korar jhono je array bitor a koyta value ase ta janar jhono
# print(np_list2, type(np_list2) , np_list2.shape)



# 2D array 

arrTwoD = np.array([[1,2,3], [4,5,6], [5,6,7], [7,8,9]])
print(arrTwoD, arrTwoD.shape)

[1 2 3 4 4 5] <class 'numpy.ndarray'> int64
[[1 2 3]
 [4 5 6]
 [5 6 7]
 [7 8 9]] (4, 3)


In [2]:
import numpy as np 

np_list = np.array([1,2,3,4,5,6,7])
print(np_list, type(np_list), np_list.dtype)




[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64
