In [1]:
import numpy as np

In [11]:
arr1 = np.ones((1,2))
print(arr1, arr1.shape)


arr2 = np.zeros((2,8))  #zerons number ashbe and 2 ta colum and 8 ta row ashbe
print(arr2, arr2.shape)


arr3 = np.full((2,8), 100) #2 ta column and 8 ta row and ashbe holo 100
print(arr3, arr3.shape)



arr4 = np.eye((3))
# [1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
print(arr4, arr4.shape)



arr5 = np.arange(1, 10, 2) #first 1 dise cz start hobe 1 theke and second 10 dise mani ses hobe 10 theke r 2 dise cz 2 step kore agabe 
print(arr5, arr5.shape)



arr6 = np.linspace(1, 100, 3) #first 1 dise cz start hobe 1 theke and second 100 dise mani ses hobe 10 theke r 3 dise mani 3 ta array hobe jemon 1 , 50, 100 
print(arr6, arr6.shape)



[[1. 1.]] (1, 2)
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] (2, 8)
[[100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100]] (2, 8)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)
