In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8])

ndx = [1,2,5]
print(arr[ndx])


[2 3 6]


In [10]:
arr1 = np.array([1,2,3,4,5,6,7,8])

print(arr1[arr1>3])
print(arr1[arr1<3])
print(arr1[arr1 %2 == 0 ])
print(arr1[arr1 %2 != 0 ])

[4 5 6 7 8]
[1 2]
[2 4 6 8]
[1 3 5 7]
