In [2]:
import numpy as np

In [8]:

arr3D = np.array([[[1,2], [3,4]],  [[5,6], [7,8]], [[9,10], [11,12]]])


print(arr3D, arr3D.shape)
#indexing
print(arr3D[0,1,0])


#slicing
print(arr3D[:, 0, :])



[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] (3, 2, 2)
3
[[ 1  2]
 [ 5  6]
 [ 9 10]]
